// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvw2uR0JoMZTfl0cOgXZnlpak04Eyh6qY',
    appId: '1:448763504669:web:abe9ce6996166bb23cfef4',
    messagingSenderId: '448763504669',
    projectId: 'lineadeprof2',
    authDomain: 'lineadeprof2.firebaseapp.com',
    storageBucket: 'lineadeprof2.appspot.com',
    measurementId: 'G-FLPCE2NLT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ej5Oypi-DmNk2mmOonKENBCGrN0nGnc',
    appId: '1:448763504669:android:db4c01c231e0c5c33cfef4',
    messagingSenderId: '448763504669',
    projectId: 'lineadeprof2',
    storageBucket: 'lineadeprof2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhyORADsx3g2tHZa0Il7oqJE98hUNKq6g',
    appId: '1:448763504669:ios:be0a99e959af9d043cfef4',
    messagingSenderId: '448763504669',
    projectId: 'lineadeprof2',
    storageBucket: 'lineadeprof2.appspot.com',
    iosClientId: '448763504669-kr35ig6mu29q5r28n77fuue92uhmkkrp.apps.googleusercontent.com',
    iosBundleId: 'com.example.lineadeprof',
  );
}
